name: God Block Mod 1.21.11 Fabric

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Download Fabric Example Mod
        run: |
          wget -O fabric-example.zip https://github.com/FabricMC/fabric-example-mod/archive/refs/heads/1.21.zip
          unzip fabric-example.zip
          cd fabric-example-mod-1.21
          rm -rf src/main/java/net
          
      - name: Create God Block Mod
        run: |
          cd fabric-example-mod-1.21
          
          # Создаем структуру папок
          mkdir -p src/main/java/com/godblock
          mkdir -p src/main/resources/assets/godblock/blockstates
          mkdir -p src/main/resources/assets/godblock/models/block
          mkdir -p src/main/resources/assets/godblock/models/item
          mkdir -p src/main/resources/assets/godblock/textures/block
          mkdir -p src/main/resources/assets/godblock/textures/item
          mkdir -p src/main/resources/assets/godblock/lang
          mkdir -p src/main/resources/data/godblock/recipe
          
          # GodMod.java
          cat > src/main/java/com/godblock/GodBlockMod.java << 'EOF'
package com.godblock;

import net.fabricmc.api.ModInitializer;
import net.minecraft.util.Identifier;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class GodBlockMod implements ModInitializer {
    public static final String MOD_ID = "godblock";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);
    
    public static final Block GOD_BLOCK = new GodBlock(
        AbstractBlock.Settings.copy(Blocks.GOLD_BLOCK)
            .strength(1000f, 3600000f)
            .luminance(state -> 15)
            .emissiveLighting((state, world, pos) -> true)
            .requiresTool()
    );
    
    @Override
    public void onInitialize() {
        Registry.register(Registries.BLOCK, 
            Identifier.of(MOD_ID, "god_block"), GOD_BLOCK);
        Registry.register(Registries.ITEM,
            Identifier.of(MOD_ID, "god_block"),
            new BlockItem(GOD_BLOCK, new Item.Settings()));
        LOGGER.info("Блок Бога загружен!");
    }
}
EOF

          # GodBlock.java
          cat > src/main/java/com/godblock/GodBlock.java << 'EOF'
package com.godblock;

import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.LightningEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.util.ActionResult;
import net.minecraft.util.Hand;
import net.minecraft.util.hit.BlockHitResult;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class GodBlock extends Block {
    public GodBlock(Settings settings) {
        super(settings);
    }

    @Override
    public ActionResult onUse(BlockState state, World world, BlockPos pos,
                            PlayerEntity player, Hand hand, BlockHitResult hit) {
        if (!world.isClient) {
            ServerWorld serverWorld = (ServerWorld) world;
            for (int i = 0; i < 3; i++) {
                LightningEntity lightning = EntityType.LIGHTNING_BOLT.create(serverWorld);
                if (lightning != null) {
                    lightning.setPos(
                        pos.getX() + 0.5 + (world.random.nextDouble() - 0.5) * 3,
                        pos.getY(),
                        pos.getZ() + 0.5 + (world.random.nextDouble() - 0.5) * 3
                    );
                    serverWorld.spawnEntity(lightning);
                }
            }
        }
        return ActionResult.SUCCESS;
    }
}
EOF

          # fabric.mod.json
          cat > src/main/resources/fabric.mod.json << 'EOF'
{
  "schemaVersion": 1,
  "id": "godblock",
  "version": "1.0.0",
  "name": "God Block",
  "description": "Божественный блок призывающий молнии!",
  "authors": ["You"],
  "license": "MIT",
  "environment": "*",
  "entrypoints": {
    "main": ["com.godblock.GodBlockMod"]
  },
  "depends": {
    "minecraft": "~1.21.1",
    "fabricloader": ">=0.15.0",
    "java": ">=21"
  }
}
EOF

          # lang files
          cat > src/main/resources/assets/godblock/lang/en_us.json << 'EOF'
{
  "block.godblock.god_block": "§6§lGod Block"
}
EOF

          cat > src/main/resources/assets/godblock/lang/ru_ru.json << 'EOF'
{
  "block.godblock.god_block": "§6§lБлок Бога"
}
EOF

          # models
          cat > src/main/resources/assets/godblock/models/block/god_block.json << 'EOF'
{
  "parent": "block/cube_all",
  "textures": {
    "all": "godblock:block/god_block"
  }
}
EOF

          cat > src/main/resources/assets/godblock/models/item/god_block.json << 'EOF'
{
  "parent": "godblock:block/god_block"
}
EOF

          # blockstate
          cat > src/main/resources/assets/godblock/blockstates/god_block.json << 'EOF'
{
  "variants": {
    "": { "model": "godblock:block/god_block" }
  }
}
EOF

          # recipe
          cat > src/main/resources/data/godblock/recipe/god_block.json << 'EOF'
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "CCC",
    "CFC",
    "CCC"
  ],
  "key": {
    "C": { "item": "minecraft:coal" },
    "F": { "item": "minecraft:flint_and_steel" }
  },
  "result": {
    "id": "godblock:god_block",
    "count": 1
  }
}
EOF

          # texture (base64 yellow block)
          echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADJSURBVDhPjZLbDcMgDEQZnVE6SkdgBI/AKEzACL3JD6oqbYiJ5JNysX3+OH4A4J7n2U9K2T6l3Cfn3D+ttTd/gTEG3znn/iilfFNK2U9K+X6RoLUeOI5jY63n1FrHtdYDEHjf95f3/c5xHIfjuB8iA4T3fe/ce9/Hfd9fEAGgY63nwL33ERHgnucZ2Pv+5R4RAVjf96O994GI8FNK+T7fP4+ICFtrPUREwPd9P+P7/j4i4iMiAiLilYgIWGs9ERHgnvs8ESkR8e8REQD3PM+JCP+PmB/yE0YJp7M27wAAAABJRU5ErkJggg==" | base64 -d > src/main/resources/assets/godblock/textures/block/god_block.png
          cp src/main/resources/assets/godblock/textures/block/god_block.png src/main/resources/assets/godblock/textures/item/god_block.png
          cp src/main/resources/assets/godblock/textures/block/god_block.png src/main/resources/assets/godblock/icon.png

      - name: Build with Gradle
        run: |
          cd fabric-example-mod-1.21
          chmod +x gradlew
          ./gradlew build --no-daemon
          
      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: God-Block-Mod-1.21.11
          path: fabric-example-mod-1.21/build/libs/*.jar